services:
  api:
    image: python:3.12-slim
    restart: always
    container_name: api
    command: bash -c "pip install poetry && poetry install && poetry run uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app
      - ./static:/app/static
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  db:
    image: postgres:16
    restart: always
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5434:5432"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html/static
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
