"""empty message

Revision ID: c29116f4214a
Revises: 440f19dbb710
Create Date: 2024-11-22 10:32:11.495637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29116f4214a'
down_revision: Union[str, None] = '440f19dbb710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('user_user', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('user_user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user_user', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('user_user', sa.Column('password', sa.String(length=128), nullable=False))
    op.add_column('user_user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_user_email'), 'user_user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_username'), 'user_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_username'), table_name='user_user')
    op.drop_index(op.f('ix_user_user_email'), table_name='user_user')
    op.drop_column('user_user', 'is_superuser')
    op.drop_column('user_user', 'is_active')
    op.drop_column('user_user', 'last_login')
    op.drop_column('user_user', 'password')
    op.drop_column('user_user', 'last_name')
    op.drop_column('user_user', 'first_name')
    op.drop_column('user_user', 'email')
    op.drop_column('user_user', 'username')
    # ### end Alembic commands ###
