"""empty message

Revision ID: 6dd95e21582e
Revises: a169ed001034
Create Date: 2024-11-25 13:39:46.091675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd95e21582e'
down_revision: Union[str, None] = 'a169ed001034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user_group',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_user_group')
    # ### end Alembic commands ###
