"""empty message

Revision ID: a169ed001034
Revises:
Create Date: 2024-11-25 11:26:12.405671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a169ed001034"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_group",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_group_name"), "auth_group", ["name"], unique=True)
    op.create_table(
        "auth_permission",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "action",
            sa.Enum("CREATE", "READ", "UPDATE", "DELETE", name="permissionaction"),
            nullable=False,
        ),
        sa.Column("object", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_permission_name"), "auth_permission", ["name"], unique=True
    )
    op.create_table(
        "user_user",
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_user_email"), "user_user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_user_username"), "user_user", ["username"], unique=True
    )
    op.create_table(
        "auth_group_permission",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["auth_group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["auth_permission.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "permission_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_group_permission")
    op.drop_index(op.f("ix_user_user_username"), table_name="user_user")
    op.drop_index(op.f("ix_user_user_email"), table_name="user_user")
    op.drop_table("user_user")
    op.drop_index(op.f("ix_auth_permission_name"), table_name="auth_permission")
    op.drop_table("auth_permission")
    op.drop_index(op.f("ix_auth_group_name"), table_name="auth_group")
    op.drop_table("auth_group")
    # ### end Alembic commands ###
